### ISSUE TITLE
It's incredibly ugly?

### ISSUE THREAD

**Issue by PySimpleGUI** [UnProgrammatore/scrcpy-gui#1]
Maybe try theme "Dark Gray 14" and use custom titlebars rather than no titlebar?

Not sure how it's supposed to look fully populated as I had to remove some code to get it to run.

![image](https://user-images.githubusercontent.com/46163555/182044653-f9948710-77a6-4996-9ba9-ca6d71fc36ed.png)

![image](https://user-images.githubusercontent.com/46163555/182044668-9dd7a1f6-5ecd-4bc2-b15c-24d262d0ea30.png)

**Comment by UnProgrammatore** [comment]
I wasn't trying to say PySimpleGUI is ugly, I was trying to say this GUI is a super-low-effort thing and I'm not gonna _try_ to make it look good

**Comment by PySimpleGUI** [comment]
I changed 1 string, the theme, and your parameters `no_titlebar=True` to `use_custom_titlebar=True`.  Not sure there's much trying required.  I like the "low effort" message more than the "ugly" one.

![image](https://user-images.githubusercontent.com/46163555/182045284-76b7fa22-8783-4aac-9a54-5fcac60f8531.png)

Glad to hear you've got plans to keep using it for other, bigger projects.

**Comment by UnProgrammatore** [comment]
I honestly didn't expect anyone to comment on a quick GUI I made to waste some time and to experiment with libraries I didn't know. Anyway, my intention wasn't definitely to comment on the quality of GUIs you can get from said library, so I updated the readme to reflect that. I appreciate you taking the time to run this and providing helpful suggestions.

**Comment by PySimpleGUI** [comment]
Just never know who's going to drop in and take a look.  I just happened to be at the right place and right time I guess to catch ya off guard.  I understood you meant you worked quickly.  No offense was taken at all.   There are things in your code others may very well be interested in.  Thanks for taking the time to have a conversation and respond so quickly.  

Good luck with your future projects!  I'm looking forward to seeing another GUI in your projects when you've got some time to spend on it.

![image](https://user-images.githubusercontent.com/46163555/182045903-41c2fc08-8973-4ce5-9bbe-3995defa08c1.png)

Take care...
